stages:
  - build
  - test
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build-job:     
  stage: build
  script: ./gradlew build


test-job:
  stage: test
  script: ./gradlew clean check