image: gradle:latest

variables:
  OPTIONS: "--no-daemon --console=plain --stacktrace"
  BEFORE_TASK: "clean"
  AFTER_TASK: ""
  GRADLE_CMD: "gradle"
  BUILD_TASK: "assemble"
  TEST_TASK: "check"

Compile:
  stage: build
  script: $GRADLE_CMD $BEFORE_TASK $BUILD_TASK $AFTER_TASK $OPTIONS

Test:
  stage: test
  script: $GRADLE_CMD $BEFORE_TASK $TEST_TASK $AFTER_TASK $OPTIONS