version: '3'

services:

  rabbit1:
    image: rabbitmq:3-management-alpine
    container_name: "rabbit1"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      - "RABBITMQ_DEFAULT_PASS=admin"
      - "RABBITMQ_DEFAULT_USER=admin"

  rabbit2:
    image: rabbitmq:3-management-alpine
    container_name: "rabbit2"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      - "RABBITMQ_DEFAULT_PASS=admin"
      - "RABBITMQ_DEFAULT_USER=admin"
      - "JOIN_CLUSTER_HOST=rabbit1"

  rabbit3:
    image: rabbitmq:3-management-alpine
    container_name: "rabbit3"
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      - "RABBITMQ_DEFAULT_PASS=admin"
      - "RABBITMQ_DEFAULT_USER=admin"
      - "JOIN_CLUSTER_HOST=rabbit1"
networks:
  rabbitmq_go_net:
    driver: bridge
